name: GitHub Actions Demo
run-name: Dusty 
on: [push]
jobs:
  Explore-GitHub-Actions: 
    runs-on: self-hosted 
    steps:
      - name: Check out repository code
        uses: actions/checkout@v4 

      - name: Login to Docker Hub 
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}

      - name: Build and Push SERVER
        uses: docker/build-push-action@v6
        with:
          context: ./studynest-api  # This is the context directory (root of repo)
          file: ./studynest-api/Dockerfile
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/studynest-api:${{ github.run_number }}
      
      -
        name: Build and push CLIENT
        uses: docker/build-push-action@v6
        with:
          context: ./studynest  # This is the context directory (root of repo)
          file: ./studynest/Dockerfile
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/studynest:${{ github.run_number }}

      -
        name: Deploy to kube?
        run:
          export PATH=$PATH:~/.nix-profile/bin:/nix/var/nix/profiles/default/bin

          export IMAGE_TAG=${{ github.run_number }}

          for file in Kubernetes/*; do 
              cat "$file" | envsubst | kubectl apply -f -; 
          done
